 

// Do not edit
// generated by https://svn.isis.vanderbilt.edu/META/sandbox/DynamicsTeam/test/GenerateDynamicsTeamTest

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Xunit;
using System.IO;
using GME.MGA;

namespace DynamicsTeamTest.Projects
{
    public class TableModelFixture : XmeImportFixture
    {
        protected override string xmeFilename
        {
            get { return Path.Combine("TableModel", "TableModel.xme"); }
        }
    }

    public partial class TableModel : IUseFixture<TableModelFixture>
    {
        internal string mgaFile { get { return this.fixture.mgaFile; } }
        private TableModelFixture fixture { get; set; }

        public void SetFixture(TableModelFixture data)
        {
            this.fixture = data;
        }

        //[Fact]
        //[Trait("Model", "TableModel")]
        //[Trait("ProjectImport/Open", "TableModel")]
        //public void ProjectXmeImport()
        //{
        //    Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
        //}

        [Fact]
        [Trait("Model", "TableModel")]
        [Trait("ProjectImport/Open", "TableModel")]
        public void ProjectMgaOpen()
        {
            var mgaReference = "MGA=" + mgaFile;

            MgaProject project = new MgaProject();
            project.OpenEx(mgaReference, "CyPhyML", null);
            project.Close(true);
            Assert.True(File.Exists(mgaReference.Substring("MGA=".Length)));
        }

        [Fact]
        [Trait("Model", "TableModel")]
        [Trait("CyPhy2Modelica", "TableModel")]
        public void Dynamics_TestBenchParameter()
        {
            string outputDir = "Dynamics_TestBenchParameter";
            string testBenchPath = "/@TestBenches|kind=Testing|relpos=0/@Dynamics|kind=Testing|relpos=0/@TestBenchParameter|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.True(result, "CyPhy2Modelica_v2 failed.");
        }

        [Fact]
        [Trait("Model", "TableModel")]
        [Trait("CyPhy2Modelica", "TableModel")]
        public void Dynamics_TestBenchProperty()
        {
            string outputDir = "Dynamics_TestBenchProperty";
            string testBenchPath = "/@TestBenches|kind=Testing|relpos=0/@Dynamics|kind=Testing|relpos=0/@TestBenchProperty|kind=TestBench|relpos=0";

            Assert.True(File.Exists(mgaFile), "Failed to generate the mga.");
            bool result = CyPhy2ModelicaRunner.Run(outputDir, mgaFile, testBenchPath);

            Assert.True(result, "CyPhy2Modelica_v2 failed.");
        }


    }
}

