//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Multibody {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Model {
        
        private ModelScript[] scriptField;
        
        private ModelContact[] contactField;
        
        private ModelTerrain terrainField;
        
        private ModelGround groundField;
        
        private ModelUnits unitsField;
        
        private ModelAssembly assemblyField;
        
        private ModelLoads loadsField;
        
        private ModelSimulation simulationField;
        
        private ModelResults resultsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Script")]
        public ModelScript[] Script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contact")]
        public ModelContact[] Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public ModelTerrain Terrain {
            get {
                return this.terrainField;
            }
            set {
                this.terrainField = value;
            }
        }
        
        /// <remarks/>
        public ModelGround Ground {
            get {
                return this.groundField;
            }
            set {
                this.groundField = value;
            }
        }
        
        /// <remarks/>
        public ModelUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public ModelAssembly Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        public ModelLoads Loads {
            get {
                return this.loadsField;
            }
            set {
                this.loadsField = value;
            }
        }
        
        /// <remarks/>
        public ModelSimulation Simulation {
            get {
                return this.simulationField;
            }
            set {
                this.simulationField = value;
            }
        }
        
        /// <remarks/>
        public ModelResults Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelScript {
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelContact {
        
        private string cyphyId1Field;
        
        private string cyphyId2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CyphyId1 {
            get {
                return this.cyphyId1Field;
            }
            set {
                this.cyphyId1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CyphyId2 {
            get {
                return this.cyphyId2Field;
            }
            set {
                this.cyphyId2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelTerrain {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelGround {
        
        private string cyphyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CyphyId {
            get {
                return this.cyphyIdField;
            }
            set {
                this.cyphyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelUnits {
        
        private string lengthField;
        
        private ModelUnitsAngle angleField;
        
        private string forceField;
        
        private string massField;
        
        private string timeField;
        
        public ModelUnits() {
            this.lengthField = "mm";
            this.forceField = "newton";
            this.massField = "kg";
            this.timeField = "sec";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelUnitsAngle Angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelUnitsAngle {
        
        /// <remarks/>
        deg,
        
        /// <remarks/>
        rad,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssembly {
        
        private ModelAssemblyJoints jointsField;
        
        /// <remarks/>
        public ModelAssemblyJoints Joints {
            get {
                return this.jointsField;
            }
            set {
                this.jointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJoints {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Joint_Locations_Only", typeof(ModelAssemblyJointsJoint_Locations_Only))]
        [System.Xml.Serialization.XmlElementAttribute("Joint_One_Axis_Given", typeof(ModelAssemblyJointsJoint_One_Axis_Given))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_Locations_Only {
        
        private ModelAssemblyJointsJoint_Locations_OnlyComponentA componentAField;
        
        private ModelAssemblyJointsJoint_Locations_OnlyComponentB componentBField;
        
        private string idField;
        
        private ModelAssemblyJointsJoint_Locations_OnlyType typeField;
        
        /// <remarks/>
        public ModelAssemblyJointsJoint_Locations_OnlyComponentA ComponentA {
            get {
                return this.componentAField;
            }
            set {
                this.componentAField = value;
            }
        }
        
        /// <remarks/>
        public ModelAssemblyJointsJoint_Locations_OnlyComponentB ComponentB {
            get {
                return this.componentBField;
            }
            set {
                this.componentBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelAssemblyJointsJoint_Locations_OnlyType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_Locations_OnlyComponentA {
        
        private string componentIDField;
        
        private string location_MetricIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location_MetricID {
            get {
                return this.location_MetricIDField;
            }
            set {
                this.location_MetricIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_Locations_OnlyComponentB {
        
        private string componentIDField;
        
        private string location_MetricIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location_MetricID {
            get {
                return this.location_MetricIDField;
            }
            set {
                this.location_MetricIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelAssemblyJointsJoint_Locations_OnlyType {
        
        /// <remarks/>
        Fixed,
        
        /// <remarks/>
        Spherical,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_One_Axis_Given {
        
        private ModelAssemblyJointsJoint_One_Axis_GivenComponentA componentAField;
        
        private ModelAssemblyJointsJoint_One_Axis_GivenComponentB componentBField;
        
        private ModelAssemblyJointsJoint_One_Axis_GivenGeometry geometryField;
        
        private string idField;
        
        private ModelAssemblyJointsJoint_One_Axis_GivenType typeField;
        
        /// <remarks/>
        public ModelAssemblyJointsJoint_One_Axis_GivenComponentA ComponentA {
            get {
                return this.componentAField;
            }
            set {
                this.componentAField = value;
            }
        }
        
        /// <remarks/>
        public ModelAssemblyJointsJoint_One_Axis_GivenComponentB ComponentB {
            get {
                return this.componentBField;
            }
            set {
                this.componentBField = value;
            }
        }
        
        /// <remarks/>
        public ModelAssemblyJointsJoint_One_Axis_GivenGeometry Geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelAssemblyJointsJoint_One_Axis_GivenType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_One_Axis_GivenComponentA {
        
        private string componentIDField;
        
        private string location_MetricIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location_MetricID {
            get {
                return this.location_MetricIDField;
            }
            set {
                this.location_MetricIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_One_Axis_GivenComponentB {
        
        private string componentIDField;
        
        private string location_MetricIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location_MetricID {
            get {
                return this.location_MetricIDField;
            }
            set {
                this.location_MetricIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelAssemblyJointsJoint_One_Axis_GivenGeometry {
        
        private string typeField;
        
        private string metricIDField;
        
        public ModelAssemblyJointsJoint_One_Axis_GivenGeometry() {
            this.typeField = "Vector";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MetricID {
            get {
                return this.metricIDField;
            }
            set {
                this.metricIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelAssemblyJointsJoint_One_Axis_GivenType {
        
        /// <remarks/>
        Translational,
        
        /// <remarks/>
        Revolute,
        
        /// <remarks/>
        Cylindrical,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelLoads {
        
        private ModelLoadsMotion[] motionField;
        
        private ModelLoadsGravity gravityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Motion")]
        public ModelLoadsMotion[] Motion {
            get {
                return this.motionField;
            }
            set {
                this.motionField = value;
            }
        }
        
        /// <remarks/>
        public ModelLoadsGravity Gravity {
            get {
                return this.gravityField;
            }
            set {
                this.gravityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelLoadsMotion {
        
        private string motionIDField;
        
        private string typeField;
        
        private string jointIDField;
        
        private ModelLoadsMotionFreedomType freedomTypeField;
        
        private ModelLoadsMotionTimeDerivative timeDerivativeField;
        
        private string functionField;
        
        private ModelLoadsMotionActive activeField;
        
        public ModelLoadsMotion() {
            this.typeField = "JointMotion";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MotionID {
            get {
                return this.motionIDField;
            }
            set {
                this.motionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string JointID {
            get {
                return this.jointIDField;
            }
            set {
                this.jointIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelLoadsMotionFreedomType FreedomType {
            get {
                return this.freedomTypeField;
            }
            set {
                this.freedomTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelLoadsMotionTimeDerivative TimeDerivative {
            get {
                return this.timeDerivativeField;
            }
            set {
                this.timeDerivativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelLoadsMotionActive Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelLoadsMotionFreedomType {
        
        /// <remarks/>
        Translational,
        
        /// <remarks/>
        Rotational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelLoadsMotionTimeDerivative {
        
        /// <remarks/>
        Displacement,
        
        /// <remarks/>
        Velocity,
        
        /// <remarks/>
        Acceleration,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelLoadsMotionActive {
        
        /// <remarks/>
        on,
        
        /// <remarks/>
        off,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelLoadsGravity {
        
        private string valueField;
        
        private ModelLoadsGravityActive activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelLoadsGravityActive Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelLoadsGravityActive {
        
        /// <remarks/>
        on,
        
        /// <remarks/>
        off,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelSimulation {
        
        private float timeField;
        
        private string stepsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResults {
        
        private ModelResultsMetric_FEA[] metric_FEAField;
        
        private ModelResultsMetric_Component_XYZ_Mag[] metric_Component_XYZ_MagField;
        
        private ModelResultsMetric_Component_Mag_Only[] metric_Component_Mag_OnlyField;
        
        private ModelResultsMetric_Point[] metric_PointField;
        
        private ModelResultsMetric_Motion[] metric_MotionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metric_FEA")]
        public ModelResultsMetric_FEA[] Metric_FEA {
            get {
                return this.metric_FEAField;
            }
            set {
                this.metric_FEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metric_Component_XYZ_Mag")]
        public ModelResultsMetric_Component_XYZ_Mag[] Metric_Component_XYZ_Mag {
            get {
                return this.metric_Component_XYZ_MagField;
            }
            set {
                this.metric_Component_XYZ_MagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metric_Component_Mag_Only")]
        public ModelResultsMetric_Component_Mag_Only[] Metric_Component_Mag_Only {
            get {
                return this.metric_Component_Mag_OnlyField;
            }
            set {
                this.metric_Component_Mag_OnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metric_Point")]
        public ModelResultsMetric_Point[] Metric_Point {
            get {
                return this.metric_PointField;
            }
            set {
                this.metric_PointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metric_Motion")]
        public ModelResultsMetric_Motion[] Metric_Motion {
            get {
                return this.metric_MotionField;
            }
            set {
                this.metric_MotionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResultsMetric_FEA {
        
        private string componentIDField;
        
        private ModelResultsMetric_FEAFEA_Tool fEA_ToolField;
        
        private ModelResultsMetric_FEAType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_FEAFEA_Tool FEA_Tool {
            get {
                return this.fEA_ToolField;
            }
            set {
                this.fEA_ToolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_FEAType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_FEAFEA_Tool {
        
        /// <remarks/>
        NASTRAN,
        
        /// <remarks/>
        ANSYS,
        
        /// <remarks/>
        ABAQUS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_FEAType {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Dynamic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResultsMetric_Component_XYZ_Mag {
        
        private string componentIDField;
        
        private ModelResultsMetric_Component_XYZ_MagM_Type m_TypeField;
        
        private ModelResultsMetric_Component_XYZ_MagM_Component m_ComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_Component_XYZ_MagM_Type M_Type {
            get {
                return this.m_TypeField;
            }
            set {
                this.m_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_Component_XYZ_MagM_Component M_Component {
            get {
                return this.m_ComponentField;
            }
            set {
                this.m_ComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_Component_XYZ_MagM_Type {
        
        /// <remarks/>
        CM_Position,
        
        /// <remarks/>
        CM_Velocity,
        
        /// <remarks/>
        CM_Acceleration,
        
        /// <remarks/>
        CM_Angular_Velocity,
        
        /// <remarks/>
        CM_Angular_Acceleration,
        
        /// <remarks/>
        Translational_Momentum,
        
        /// <remarks/>
        Angular_Momentum_About_CM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_Component_XYZ_MagM_Component {
        
        /// <remarks/>
        X,
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        Mag,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResultsMetric_Component_Mag_Only {
        
        private string componentIDField;
        
        private ModelResultsMetric_Component_Mag_OnlyM_Type m_TypeField;
        
        private string m_ComponentField;
        
        public ModelResultsMetric_Component_Mag_Only() {
            this.m_ComponentField = "Mag";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_Component_Mag_OnlyM_Type M_Type {
            get {
                return this.m_TypeField;
            }
            set {
                this.m_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M_Component {
            get {
                return this.m_ComponentField;
            }
            set {
                this.m_ComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_Component_Mag_OnlyM_Type {
        
        /// <remarks/>
        Kinetic_Energy,
        
        /// <remarks/>
        Translational_Kinetic_Energy,
        
        /// <remarks/>
        Angular_Kinetic_Energy,
        
        /// <remarks/>
        Potential_Energy_Delta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResultsMetric_Point {
        
        private string point_MetricIDField;
        
        private ModelResultsMetric_PointM_Type m_TypeField;
        
        private ModelResultsMetric_PointM_Component m_ComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Point_MetricID {
            get {
                return this.point_MetricIDField;
            }
            set {
                this.point_MetricIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_PointM_Type M_Type {
            get {
                return this.m_TypeField;
            }
            set {
                this.m_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModelResultsMetric_PointM_Component M_Component {
            get {
                return this.m_ComponentField;
            }
            set {
                this.m_ComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_PointM_Type {
        
        /// <remarks/>
        Total_Force_At_Location,
        
        /// <remarks/>
        Total_Torque_At_Location,
        
        /// <remarks/>
        Translational_Displacement,
        
        /// <remarks/>
        Translational_Velocity,
        
        /// <remarks/>
        Translational_Acceleration,
        
        /// <remarks/>
        Angular_Velocity,
        
        /// <remarks/>
        Angular_Acceleration,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ModelResultsMetric_PointM_Component {
        
        /// <remarks/>
        X,
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        Mag,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModelResultsMetric_Motion {
        
        private string motionIDField;
        
        private string m_TypeField;
        
        private string m_ComponentField;
        
        public ModelResultsMetric_Motion() {
            this.m_TypeField = "Power_Consumption";
            this.m_ComponentField = "Mag";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MotionID {
            get {
                return this.motionIDField;
            }
            set {
                this.motionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M_Type {
            get {
                return this.m_TypeField;
            }
            set {
                this.m_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M_Component {
            get {
                return this.m_ComponentField;
            }
            set {
                this.m_ComponentField = value;
            }
        }
    }
}
