//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Complexity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ComponentInstance
	{
		public virtual string AVMID
		{
			get;
			set;
		}

		public virtual string InstanceID
		{
			get;
			set;
		}

		public virtual Double Complexity
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual DistributionTypeEnum DistributionType
		{
			get;
			set;
		}

		public virtual IEnumerable<Double> DistributionParameters
		{
			get;
			set;
		}

	}
}

