///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "3F83A74A-0F1D-4A02-B82B-3144C8E22C3C"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (CAD2CyPhy)"
#define COCLASS_UUID "4E6F06F8-8378-42FB-9E5D-1CDB464C5A42"
#define COCLASS_NAME "MGA Interpreter CoClass (CAD2CyPhy)"
#define COCLASS_PROGID "MGA.Interpreter.CAD2CyPhy"

#define COCLASS_UUID_EXPLODED1  0x4e6f06f8
#define COCLASS_UUID_EXPLODED2   0x8378
#define COCLASS_UUID_EXPLODED3   0x42fb
#define COCLASS_UUID_EXPLODED4   0x9e
#define COCLASS_UUID_EXPLODED5   0x5d
#define COCLASS_UUID_EXPLODED6   0x1c
#define COCLASS_UUID_EXPLODED7   0xdb
#define COCLASS_UUID_EXPLODED8   0x46
#define COCLASS_UUID_EXPLODED9   0x4c
#define COCLASS_UUID_EXPLODED10  0x5a
#define COCLASS_UUID_EXPLODED11  0x42


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "CAD2CyPhy"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "CAD2CyPhy Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "CyPhyML"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
