//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META
{
	using AVM;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class BehaviorModel : Model
	{
		public virtual List<Interface> Interfaces
		{
			get;
			set;
		}

		public virtual List<Phenomenon> Phenomena
		{
			get;
			set;
		}

		public virtual List<MaterialSpec> MaterialSpecs
		{
			get;
			set;
		}

		public virtual List<LimitCheck> LimitChecks
		{
			get;
			set;
		}

	}
}

