//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META
{
	using AVM;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BehaviorParameter : Interface
	{
		public virtual String Unit
		{
			get;
			set;
		}

		public virtual String ValidRange
		{
			get;
			set;
		}

		public virtual string Value
		{
			get;
			set;
		}

		public virtual Boolean? IsInitialization
		{
			get;
			set;
		}

		public virtual string VarInitialized
		{
			get;
			set;
		}

		public virtual String Description
		{
			get;
			set;
		}

		public virtual String NativeToolUnit
		{
			get;
			set;
		}

		public virtual String Dimension
		{
			get;
			set;
		}

		public virtual String DefaultValue
		{
			get;
			set;
		}

	}
}

