//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META
{
	using AVM;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class CADModel : Model
	{
		public virtual CADModelType ModelType
		{
			get;
			set;
		}

		public virtual List<Metric> Metrics
		{
			get;
			set;
		}

		public virtual List<CADParameter> CADParameters
		{
			get;
			set;
		}

		public virtual List<Datum> Datums
		{
			get;
			set;
		}

	}
}

