//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum DirectionEnum
	{
		Input,
		Output,
	}
}
