//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META
{
	using AVM;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Interface : Associable
	{
		public virtual string Name
		{
			get;
			set;
		}

	}
}

