// Component configuration file automatically generated as ComponentConfig.h
// by ConfigureComponent on Thu Sep 21 14:32:46 2000


// COM UUID-s, names and progID



// TODO: Modify these macros
// !!! ALWAYS REPLACE THE UUID STRINGS WITH NEW UNIQUE IDS (These new GUIDs can be generated by the guidgen tool)
#define TYPELIB_UUID "F06E7A6E-E33C-4813-ADDB-AA119FB0ECB7"
#define TYPELIB_NAME "MGA Decorator TypeLibrary (CPMDecorator)"
#define COCLASS_UUID "BF4CBC84-0816-4FAD-A088-F61598B29F51"
#define COCLASS_NAME "MGA Decorator CoClass (CPMDecorator)"
#define COCLASS_PROGID "MGA.CPMDecorator"

#define CONSTOLESTR(X)		OLESTR(X)


// This name will appear in the popup window for interpreter selection.
#define DECORATOR_NAME "CPMDecorator"

