///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "161D2450-7871-4F86-AB95-2BA3DB87758C"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (SFTableEditor)"
#define COCLASS_UUID "C6F0DBA2-3D10-455E-8096-EB8D78D7624B"
#define COCLASS_NAME "MGA Interpreter CoClass (SFTableEditor)"
#define COCLASS_PROGID "MGA.Interpreter.SFTableEditor"

#define COCLASS_UUID_EXPLODED1  0xc6f0dba2
#define COCLASS_UUID_EXPLODED2   0x3d10
#define COCLASS_UUID_EXPLODED3   0x455e
#define COCLASS_UUID_EXPLODED4   0x80
#define COCLASS_UUID_EXPLODED5   0x96
#define COCLASS_UUID_EXPLODED6   0xeb
#define COCLASS_UUID_EXPLODED7   0x8d
#define COCLASS_UUID_EXPLODED8   0x78
#define COCLASS_UUID_EXPLODED9   0xd7
#define COCLASS_UUID_EXPLODED10  0x62
#define COCLASS_UUID_EXPLODED11  0x4b


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "SignalFlow Table Editor"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "SignalFlow Table Editor PlugIn"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
