///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "3894F514-AC5B-46A6-8387-69BA10284531"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (CyberPortTypeChecker)"
#define COCLASS_UUID "4E51BF6F-68CF-484E-9EC4-0BD6D64AAD33"
#define COCLASS_NAME "MGA Interpreter CoClass (CyberPortTypeChecker)"
#define COCLASS_PROGID "MGA.Interpreter.CyberPortTypeChecker"

#define COCLASS_UUID_EXPLODED1  0x4e51bf6f
#define COCLASS_UUID_EXPLODED2   0x68cf
#define COCLASS_UUID_EXPLODED3   0x484e
#define COCLASS_UUID_EXPLODED4   0x9e
#define COCLASS_UUID_EXPLODED5   0xc4
#define COCLASS_UUID_EXPLODED6   0xb
#define COCLASS_UUID_EXPLODED7   0xd6
#define COCLASS_UUID_EXPLODED8   0xd6
#define COCLASS_UUID_EXPLODED9   0x4a
#define COCLASS_UUID_EXPLODED10  0xad
#define COCLASS_UUID_EXPLODED11  0x33


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "CyberPortTypeChecker"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "Cyber Port Type Checker"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "CyberComposition"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
