{	
	"metrics_file" : "CADAssembly_metrics.xml",
    "path_to_instance_xmls" : "ComponentACMs",
    "path_to_instance_stls" : "STL_BINARY",
    "instance_file" : "component_index.json",
    "output_json_file" : "output.json",
	"mil_std" : {
                "01_SRP_to_roof" : {
                                        "min" : 0.960,
                                        "max" : 1.173},
                "02_seat_to_steering_wheel" : {
                                        "min" : 0.366,
                                        "max" : 0.447},
                "03_seat_to_dash" : {
                                        "min" : 0.663,
                                        "max" : 0.810},
                "04_seat_to_under_steering_wheel" : {
                                        "min" : 0.217,
                                        "max" : 0.265},
                "05_seat_height" : {
                                        "min" : 0.152,
                                        "max" : 0.381},
                "06_seat_to_accel" : {
                                        "min" : 0.320,
                                        "max" : 0.391},
                "07_steering_clearance" : {
                                        "min" : 0.069,
                                        "max" : 0.084},
                "08_brake_to_under_steering_wheel" : {
                                        "min" : 0.594,
                                        "max" : 0.726},
                "09_driver_center_to_brake_right" : {
                                        "min" : 0.137,
                                        "max" : 0.168},
                "10_brake_right_to_accel_right" : {
                                        "min" : 0.137,
                                        "max" : 0.168}}
}
