///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "97f4315e-864e-4ee6-ac1f-a3c12bacace7"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (Cyber2SLC_CodeGen)"
#define COCLASS_UUID "1a98a829-6ffa-42e9-8f97-8a8804d44662"
#define COCLASS_NAME "MGA Interpreter CoClass (Cyber2SLC_CodeGen)"
#define COCLASS_PROGID "MGA.Interpreter.Cyber2SLC_CodeGen"

#define COCLASS_UUID_EXPLODED1  0x1a98a829
#define COCLASS_UUID_EXPLODED2   0x6ffa
#define COCLASS_UUID_EXPLODED3   0x42e9
#define COCLASS_UUID_EXPLODED4   0x8f
#define COCLASS_UUID_EXPLODED5   0x97
#define COCLASS_UUID_EXPLODED6   0x8a
#define COCLASS_UUID_EXPLODED7   0x88
#define COCLASS_UUID_EXPLODED8   0x04
#define COCLASS_UUID_EXPLODED9   0xd4
#define COCLASS_UUID_EXPLODED10  0x46
#define COCLASS_UUID_EXPLODED11  0x62


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "Cyber2SLC_CodeGen"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "Cyber2SLC_Code Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "CyberComposition"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
