///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "2ACA78CF-EC8E-4E0C-9840-A251E5807055"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (CyPhyFormulaEvaluator)"
#define COCLASS_UUID "7D316640-9593-4324-88CE-72988CA252E7"
#define COCLASS_NAME "MGA Interpreter CoClass (CyPhyFormulaEvaluator)"
#define COCLASS_PROGID "MGA.Interpreter.CyPhyFormulaEvaluator"

#define COCLASS_UUID_EXPLODED1  0x7d316640
#define COCLASS_UUID_EXPLODED2   0x9593
#define COCLASS_UUID_EXPLODED3   0x4324
#define COCLASS_UUID_EXPLODED4   0x88
#define COCLASS_UUID_EXPLODED5   0xce
#define COCLASS_UUID_EXPLODED6   0x72
#define COCLASS_UUID_EXPLODED7   0x98
#define COCLASS_UUID_EXPLODED8   0x8c
#define COCLASS_UUID_EXPLODED9   0xa2
#define COCLASS_UUID_EXPLODED10  0x52
#define COCLASS_UUID_EXPLODED11  0xe7


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "CyPhyFormulaEvaluator"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "CyPhyFormulaEvaluator Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER
//#define GME_ADDON

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "CyPhyML"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
