//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM
{
	using AVM.META;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract partial class Associable
	{
		public virtual String id
		{
			get;
			set;
		}

	}
}

