//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Component
	{
		public virtual String AVMID
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual List<string> Category
		{
			get;
			set;
		}

		public virtual String Version
		{
			get;
			set;
		}

		public virtual String Revision
		{
			get;
			set;
		}

		public virtual String DDPSpecVersion
		{
			get;
			set;
		}

		public virtual List<Feature> Features
		{
			get;
			set;
		}

		public virtual List<Association> Associations
		{
			get;
			set;
		}

		public virtual List<File> Files
		{
			get;
			set;
		}

		public virtual List<Supercede> Supercedes
		{
			get;
			set;
		}

	}
}

