//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Supercede
	{
		public virtual String Reason
		{
			get;
			set;
		}

		public virtual string AVMID
		{
			get;
			set;
		}

	}
}

