///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "8955EDD6-DAEC-49EE-9952-8C6AA3C87056"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (CyPhyElaborate)"
#define COCLASS_UUID "FF67D6C7-B2D1-407C-A1B0-B7B728C0FA4F"
#define COCLASS_NAME "MGA Interpreter CoClass (CyPhyElaborate)"
#define COCLASS_PROGID "MGA.Interpreter.CyPhyElaborate"

#define COCLASS_UUID_EXPLODED1  0xff67d6c7
#define COCLASS_UUID_EXPLODED2   0xb2d1
#define COCLASS_UUID_EXPLODED3   0x407c
#define COCLASS_UUID_EXPLODED4   0xa1
#define COCLASS_UUID_EXPLODED5   0xb0
#define COCLASS_UUID_EXPLODED6   0xb7
#define COCLASS_UUID_EXPLODED7   0xb7
#define COCLASS_UUID_EXPLODED8   0x28
#define COCLASS_UUID_EXPLODED9   0xc0
#define COCLASS_UUID_EXPLODED10  0xfa
#define COCLASS_UUID_EXPLODED11  0x4f


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME L"CyPhyElaborate"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "CyPhyElaborate"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER
//#define GME_ADDON

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "CyPhyML"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
