#include <CreoErrorCodes.h>

namespace isis
{

	static struct Pro_Tk_Error {
		int error;
		const char* message;
	} Pro_Tk_Errors[] = {
		{ PRO_TK_NO_ERROR, "PRO_TK_NO_ERROR" },
		{ PRO_TK_GENERAL_ERROR, "PRO_TK_GENERAL_ERROR" },
		{ PRO_TK_BAD_INPUTS, "PRO_TK_BAD_INPUTS" },
		{ PRO_TK_USER_ABORT, "PRO_TK_USER_ABORT" },
		{ PRO_TK_E_NOT_FOUND, "PRO_TK_E_NOT_FOUND" },
		{ PRO_TK_E_FOUND, "PRO_TK_E_FOUND" },
		{ PRO_TK_LINE_TOO_LONG, "PRO_TK_LINE_TOO_LONG" },
		{ PRO_TK_CONTINUE, "PRO_TK_CONTINUE" },
		{ PRO_TK_BAD_CONTEXT, "PRO_TK_BAD_CONTEXT" },
		{ PRO_TK_NOT_IMPLEMENTED, "PRO_TK_NOT_IMPLEMENTED" },
		{ PRO_TK_OUT_OF_MEMORY, "PRO_TK_OUT_OF_MEMORY" },
		{ PRO_TK_COMM_ERROR, "PRO_TK_COMM_ERROR" },
		{ PRO_TK_NO_CHANGE, "PRO_TK_NO_CHANGE" },
		{ PRO_TK_SUPP_PARENTS, "PRO_TK_SUPP_PARENTS" },
		{ PRO_TK_PICK_ABOVE, "PRO_TK_PICK_ABOVE" },
		{ PRO_TK_INVALID_DIR, "PRO_TK_INVALID_DIR" },
		{ PRO_TK_INVALID_FILE, "PRO_TK_INVALID_FILE" },
		{ PRO_TK_CANT_WRITE, "PRO_TK_CANT_WRITE" },
		{ PRO_TK_INVALID_TYPE, "PRO_TK_INVALID_TYPE" },
		{ PRO_TK_INVALID_PTR, "PRO_TK_INVALID_PTR" },
		{ PRO_TK_UNAV_SEC, "PRO_TK_UNAV_SEC" },
		{ PRO_TK_INVALID_MATRIX, "PRO_TK_INVALID_MATRIX" },
		{ PRO_TK_INVALID_NAME, "PRO_TK_INVALID_NAME" },
		{ PRO_TK_NOT_EXIST, "PRO_TK_NOT_EXIST" },
		{ PRO_TK_CANT_OPEN, "PRO_TK_CANT_OPEN" },
		{ PRO_TK_ABORT, "PRO_TK_ABORT" },
		{ PRO_TK_NOT_VALID, "PRO_TK_NOT_VALID" },
		{ PRO_TK_INVALID_ITEM, "PRO_TK_INVALID_ITEM" },
		{ PRO_TK_MSG_NOT_FOUND, "PRO_TK_MSG_NOT_FOUND" },
		{ PRO_TK_MSG_NO_TRANS, "PRO_TK_MSG_NO_TRANS" },
		{ PRO_TK_MSG_FMT_ERROR, "PRO_TK_MSG_FMT_ERROR" },
		{ PRO_TK_MSG_USER_QUIT, "PRO_TK_MSG_USER_QUIT" },
		{ PRO_TK_MSG_TOO_LONG, "PRO_TK_MSG_TOO_LONG" },
		{ PRO_TK_CANT_ACCESS, "PRO_TK_CANT_ACCESS" },
		{ PRO_TK_OBSOLETE_FUNC, "PRO_TK_OBSOLETE_FUNC" },
		{ PRO_TK_NO_COORD_SYSTEM, "PRO_TK_NO_COORD_SYSTEM" },
		{ PRO_TK_E_AMBIGUOUS, "PRO_TK_E_AMBIGUOUS" },
		{ PRO_TK_E_DEADLOCK, "PRO_TK_E_DEADLOCK" },
		{ PRO_TK_E_BUSY, "PRO_TK_E_BUSY" },
		{ PRO_TK_E_IN_USE, "PRO_TK_E_IN_USE" },
		{ PRO_TK_NO_LICENSE, "PRO_TK_NO_LICENSE" },
		{ PRO_TK_BSPL_UNSUITABLE_DEGREE, "PRO_TK_BSPL_UNSUITABLE_DEGREE" },
		{ PRO_TK_BSPL_NON_STD_END_KNOTS, "PRO_TK_BSPL_NON_STD_END_KNOTS" },
		{ PRO_TK_BSPL_MULTI_INNER_KNOTS, "PRO_TK_BSPL_MULTI_INNER_KNOTS" },
		{ PRO_TK_BAD_SRF_CRV, "PRO_TK_BAD_SRF_CRV" },
		{ PRO_TK_EMPTY, "PRO_TK_EMPTY" },
		{ PRO_TK_BAD_DIM_ATTACH, "PRO_TK_BAD_DIM_ATTACH" },
		{ PRO_TK_NOT_DISPLAYED, "PRO_TK_NOT_DISPLAYED" },
		{ PRO_TK_CANT_MODIFY, "PRO_TK_CANT_MODIFY" },
		{ PRO_TK_CHECKOUT_CONFLICT, "PRO_TK_CHECKOUT_CONFLICT" },
		{ PRO_TK_CRE_VIEW_BAD_SHEET, "PRO_TK_CRE_VIEW_BAD_SHEET" },
		{ PRO_TK_CRE_VIEW_BAD_MODEL, "PRO_TK_CRE_VIEW_BAD_MODEL" },
		{ PRO_TK_CRE_VIEW_BAD_PARENT, "PRO_TK_CRE_VIEW_BAD_PARENT" },
		{ PRO_TK_CRE_VIEW_BAD_TYPE, "PRO_TK_CRE_VIEW_BAD_TYPE" },
		{ PRO_TK_CRE_VIEW_BAD_EXPLODE, "PRO_TK_CRE_VIEW_BAD_EXPLODE" },
		{ PRO_TK_UNATTACHED_FEATS, "PRO_TK_UNATTACHED_FEATS" },
		{ PRO_TK_REGEN_AGAIN, "PRO_TK_REGEN_AGAIN" },
		{ PRO_TK_DWGCREATE_ERRORS, "PRO_TK_DWGCREATE_ERRORS" },
		{ PRO_TK_UNSUPPORTED, "PRO_TK_UNSUPPORTED" },
		{ PRO_TK_NO_PERMISSION, "PRO_TK_NO_PERMISSION" },
		{ PRO_TK_AUTHENTICATION_FAILURE, "PRO_TK_AUTHENTICATION_FAILURE" },
		{ PRO_TK_OUTDATED, "PRO_TK_OUTDATED" },
		{ PRO_TK_INCOMPLETE, "PRO_TK_INCOMPLETE" },
		{ PRO_TK_CHECK_OMITTED, "PRO_TK_CHECK_OMITTED" },
		{ PRO_TK_MAX_LIMIT_REACHED, "PRO_TK_MAX_LIMIT_REACHED" },
		{ PRO_TK_OUT_OF_RANGE, "PRO_TK_OUT_OF_RANGE" },
		{ PRO_TK_CHECK_LAST_ERROR, "PRO_TK_CHECK_LAST_ERROR" },
		{ PRO_TK_APP_CREO_BARRED, "PRO_TK_APP_CREO_BARRED" },
		{ PRO_TK_APP_TOO_OLD, "PRO_TK_APP_TOO_OLD" },
		{ PRO_TK_APP_BAD_DATAPATH, "PRO_TK_APP_BAD_DATAPATH" },
		{ PRO_TK_APP_BAD_ENCODING, "PRO_TK_APP_BAD_ENCODING" },
		{ PRO_TK_APP_NO_LICENSE, "PRO_TK_APP_NO_LICENSE" },
		{ PRO_TK_APP_XS_CALLBACKS, "PRO_TK_APP_XS_CALLBACKS" },
		{ PRO_TK_APP_STARTUP_FAIL, "PRO_TK_APP_STARTUP_FAIL" },
		{ PRO_TK_APP_INIT_FAIL, "PRO_TK_APP_INIT_FAIL" },
		{ PRO_TK_APP_VERSION_MISMATCH, "PRO_TK_APP_VERSION_MISMATCH" },
		{ PRO_TK_APP_COMM_FAILURE, "PRO_TK_APP_COMM_FAILURE" },
		{ PRO_TK_APP_NEW_VERSION, "PRO_TK_APP_NEW_VERSION" },
		{ PRO_TK_APP_UNLOCK, "PRO_TK_APP_UNLOCK" },
		{ PRO_TK_APP_JLINK_NOT_ALLOWED, "PRO_TK_APP_JLINK_NOT_ALLOWED" },
		{ NULL, NULL }
	};

	const std::string ProToolKitError_string(ProErrors in_Error)
	{
		for (struct Pro_Tk_Error* i = &Pro_Tk_Errors[0]; i->message; i++)
		{
			if (i->error == in_Error)
			{
				return i->message;
			}
		}
		return "Unknown error";
	}


} // END namespace isis