//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Complexity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Design
	{
		public virtual string AVMID
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual IEnumerable<ComponentInstance> ComponentInstances
		{
			get;
			set;
		}

		public virtual IEnumerable<Connection> Connections
		{
			get;
			set;
		}

	}
}

