//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.VehicleForge
{
	using AVM.META;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class ITAR_Restriction : DistributionRestriction
	{
		public virtual ITARRestrictionLevelEnum Level
		{
			get;
			set;
		}

		public virtual List<String> Documentation
		{
			get;
			set;
		}

	}
}

