//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.VehicleForge
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Proprietary : DistributionRestriction
	{
		public virtual string Organization
		{
			get;
			set;
		}

	}
}

