import "oaidl.idl";
import "ocidl.idl";

#include "ComponentConfig.h"
#include "InterfaceColl.h"

import "core.idl";
import "mga.idl";

[
	object,
	uuid(7C39978A-9988-47C5-9443-D145F32A82A0),
	oleautomation,
	pointer_default(unique)
]
interface IDesignSpaceHelper : IMgaComponentEx
{
	HRESULT ApplyConstraintsAndGenerateCWCs([in] IMgaProject *project, [in] IMgaFCO *currentobj, [in] VARIANT_BOOL applyConstraints);
	HRESULT ExportDesertXML([in] IMgaProject *project, [in] IMgaFCO *currentobj, [in] BSTR exportPath);
	HRESULT ImportConfigsFromXML([in] IMgaProject *project, [in] IMgaFCO *designContainer, [in] BSTR desertXmlPath, [in] BSTR desertBackXmlPath, [out, retval] BSTR *exportedConfigurationsName);
}

[
	uuid(TYPELIB_UUID),
	// n.b. synchronize this value with QueryPathOfRegTypeLib call and deploy/DesignSpaceHelper.wxi
	version(1.2),
	helpstring(TYPELIB_NAME)
]
library MgaComponentLib
{
	importlib("stdole32.tlb");
	importlib("core.dll");
	importlib("meta.dll");
	importlib("mga.dll");

	[
		uuid(COCLASS_UUID),
		helpstring(COCLASS_NAME)
	]
	coclass MgaComponent
	{
		[default] interface IMgaComponentEx;
		interface IMgaComponent;
		interface IGMEVersionInfo;
	};

	interface IDesignSpaceHelper;
};


