//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax-loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;project&gt;
        ///    &lt;actions/&gt;
        ///    &lt;description&gt;{0}&lt;/description&gt;
        ///    &lt;keepDependencies&gt;false&lt;/keepDependencies&gt;
        ///    &lt;properties&gt;
        ///        &lt;hudson.model.ParametersDefinitionProperty&gt;
        ///            &lt;parameterDefinitions&gt;
        ///              &lt;hudson.model.StringParameterDefinition&gt;
        ///                &lt;name&gt;resultsPutUrl&lt;/name&gt;
        ///                &lt;description/&gt;
        ///                &lt;defaultValue/&gt;
        ///              &lt;/hudson.model.StringParameterDefinition&gt;
        ///              &lt;hudson.model.Stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string job_config {
            get {
                return ResourceManager.GetString("job_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;project&gt;
        ///	&lt;keepDependencies&gt;false&lt;/keepDependencies&gt;
        ///	&lt;properties/&gt;
        ///	&lt;scm class=&apos;jenkins.scm.NullSCM&apos;/&gt;
        ///	&lt;canRoam&gt;true&lt;/canRoam&gt;
        ///	&lt;disabled&gt;false&lt;/disabled&gt;
        ///	&lt;blockBuildWhenUpstreamBuilding&gt;false&lt;/blockBuildWhenUpstreamBuilding&gt;
        ///	&lt;triggers class=&apos;vector&apos;/&gt;
        ///	&lt;concurrentBuild&gt;false&lt;/concurrentBuild&gt;
        ///	&lt;builders/&gt;
        ///	&lt;publishers/&gt;
        ///	&lt;buildWrappers/&gt;
        ///&lt;/project&gt;.
        /// </summary>
        internal static string sample_config {
            get {
                return ResourceManager.GetString("sample_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zip {
            get {
                object obj = ResourceManager.GetObject("zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
