//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META.Design
{
	using AVM;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class ComponentInstance
	{
		public virtual String ComponentID
		{
			get;
			set;
		}

		public virtual String Definition
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual string SrcDesignSpaceContainerID
		{
			get;
			set;
		}

		public virtual String ComponentRevision
		{
			get;
			set;
		}

		public virtual String ComponentVersion
		{
			get;
			set;
		}

		public virtual string id
		{
			get;
			set;
		}

		public virtual List<PortInstance> PortInstances
		{
			get;
			set;
		}

		public virtual List<ComponentNamedValueInstance> NamedValueInstances
		{
			get;
			set;
		}

		public virtual List<StructuralInterfaceInstance> StructuralInterfaceInstances
		{
			get;
			set;
		}

	}
}

