//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META.Design
{
	using AVM.META;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ComponentNamedValueInstance : META.Design.ValueType
	{
		public virtual string IDinComponentModel
		{
			get;
			set;
		}

		public virtual Double Value
		{
			get;
			set;
		}

		public virtual ComponentInstance ComponentInstance
		{
			get;
			set;
		}

	}
}

