//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AVM.META.Design
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class PortConnector : Connector
	{
		public virtual List<AbstractPort> EndPoints
		{
			get;
			set;
		}

	}
}

