//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace JobManager
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JobManagerEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JobManagerEntities1 object using the connection string found in the 'JobManagerEntities1' section of the application configuration file.
        /// </summary>
        public JobManagerEntities1() : base("name=JobManagerEntities1", "JobManagerEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobManagerEntities1 object.
        /// </summary>
        public JobManagerEntities1(string connectionString) : base(connectionString, "JobManagerEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobManagerEntities1 object.
        /// </summary>
        public JobManagerEntities1(EntityConnection connection) : base(connection, "JobManagerEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SavedJob> SavedJobs
        {
            get
            {
                if ((_SavedJobs == null))
                {
                    _SavedJobs = base.CreateObjectSet<SavedJob>("SavedJobs");
                }
                return _SavedJobs;
            }
        }
        private ObjectSet<SavedJob> _SavedJobs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SavedJobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSavedJobs(SavedJob savedJob)
        {
            base.AddObject("SavedJobs", savedJob);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobManagerModel", Name="SavedJob")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SavedJob : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SavedJob object.
        /// </summary>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="workingDirectory">Initial value of the WorkingDirectory property.</param>
        /// <param name="runCommand">Initial value of the RunCommand property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="jobName">Initial value of the JobName property.</param>
        public static SavedJob CreateSavedJob(global::System.String title, global::System.String workingDirectory, global::System.String runCommand, global::System.String status, global::System.String jobName)
        {
            SavedJob savedJob = new SavedJob();
            savedJob.Title = title;
            savedJob.WorkingDirectory = workingDirectory;
            savedJob.RunCommand = runCommand;
            savedJob.Status = status;
            savedJob.JobName = jobName;
            return savedJob;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkingDirectory
        {
            get
            {
                return _WorkingDirectory;
            }
            set
            {
                OnWorkingDirectoryChanging(value);
                ReportPropertyChanging("WorkingDirectory");
                _WorkingDirectory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkingDirectory");
                OnWorkingDirectoryChanged();
            }
        }
        private global::System.String _WorkingDirectory;
        partial void OnWorkingDirectoryChanging(global::System.String value);
        partial void OnWorkingDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RunCommand
        {
            get
            {
                return _RunCommand;
            }
            set
            {
                OnRunCommandChanging(value);
                ReportPropertyChanging("RunCommand");
                _RunCommand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RunCommand");
                OnRunCommandChanged();
            }
        }
        private global::System.String _RunCommand;
        partial void OnRunCommandChanging(global::System.String value);
        partial void OnRunCommandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobName
        {
            get
            {
                return _JobName;
            }
            set
            {
                if (_JobName != value)
                {
                    OnJobNameChanging(value);
                    ReportPropertyChanging("JobName");
                    _JobName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("JobName");
                    OnJobNameChanged();
                }
            }
        }
        private global::System.String _JobName;
        partial void OnJobNameChanging(global::System.String value);
        partial void OnJobNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VFUrl
        {
            get
            {
                return _VFUrl;
            }
            set
            {
                OnVFUrlChanging(value);
                ReportPropertyChanging("VFUrl");
                _VFUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VFUrl");
                OnVFUrlChanged();
            }
        }
        private global::System.String _VFUrl;
        partial void OnVFUrlChanging(global::System.String value);
        partial void OnVFUrlChanged();

        #endregion
    
    }

    #endregion
    
}
